### ISSUE TITLE
Alternate Pins

### ISSUE THREAD

**Issue by taylorknopp** [michalhol/ps2kbdlib#3]
I'm working on a project, in which I would like to use this library. Almost all my pins are used up by other things, so I was have the ps2 port wired to pin 34(CLK),35(DATA). Currently I can;t get any keyboard data.  I have tried running your example code with just the pins definitions changed. shoudl this library be able to be used with any pins on the esp? or is there only a subset of pins that will work. If only certain pins work what are they?

**Comment by cubicap** [comment]
Hi, as far, as I remember, it should work with any pins, if one connected to CLK supports interrupts. 
I think, almost all pins on ESP32 support those, so the only thing I can think of is that, there could be something disabling interrupts.

**Comment by cubicap** [comment]
Oh... You tried to run the example alone. Then there is nothing to disable interrupts. 
You could try changing the pins to other ones but that may not be well possible in your case

**Comment by cubicap** [comment]
The problem may be caused by the pins 34 and higher being input only, which means, they will definitely not support OUTPUT_OPEN_DRAIN pin mode.

You can try setting the pins to different ones.

The other possible solution may be changing the pin mode (PS2Kbd.cpp, lines 335 and 336) to INPUT_PULLUP but I cannot guarantee that it will help.
